Update docs for use cases with EURAC
interTwin-eu/itwinai pull request #253
Opened 2024-11-20 13:19 UTC by jarlsondre

# Summary
Add EURAC to the list of use cases found in the docs and change the use-cases page slightly for a (IMO) cleaner look.

# Noteworthy
I chose to not add more than the readme for EURAC as I found that adding the code files is messy and doesn't add anything. Personally, I feel that if someone wants to explore the code, they can either do it on GitHub or (even better) in their own text editor.

2024-11-20 16:12 UTC, matbun commented on docs/index.rst
> -   getting-started/plugins
:(

2024-11-20 16:14 UTC, matbun commented
> I chose to not add more than the readme for EURAC as I found that adding the code files is messy and doesn't add anything. Personally, I feel that if someone wants to explore the code, they can either do it on GitHub or (even better) in their own text editor.

I agree, could you clean that up for the other use cases as well, please? Still, it would be nice to have a link to the repo's directory of the use case, for each use case, if possible

2024-11-20 16:17 UTC, jarlsondre commented
> > I chose to not add more than the readme for EURAC as I found that adding the code files is messy and doesn't add anything. Personally, I feel that if someone wants to explore the code, they can either do it on GitHub or (even better) in their own text editor.
> 
> I agree, could you clean that up for the other use cases as well, please? Still, it would be nice to have a link to the repo's directory of the use case, for each use case, if possible

I agree with adding the GitHub link. I actually thought I wrote that, but I see now that I only wrote it in my personal notes, hahaha

2024-11-26 08:22 UTC, matbun commented on docs/index.rst
> -   getting-started/plugins
you should clone with `--recurse-submodules`

2024-11-26 08:23 UTC, matbun requested changes
Apart from the plugins which should be added back, it looks good to me

2024-11-28 16:05 UTC, matbun approved these changes

2024-11-28 16:21 UTC, merged